### ISSUE TITLE
App crash when saving received session

### ISSUE THREAD

**Issue by Tornaco** [Tornaco/DataMigration#1]
```
04-17 21:44:16.529  6538  6573 E AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
04-17 21:44:16.529  6538  6573 E AndroidRuntime: Process: org.newstand.datamigration, PID: 6538
04-17 21:44:16.529  6538  6573 E AndroidRuntime: io.realm.exceptions.RealmError: Unrecoverable error. Invalid argument in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 109
04-17 21:44:16.529  6538  6573 E AndroidRuntime: 	at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
04-17 21:44:16.529  6538  6573 E AndroidRuntime: 	at io.realm.internal.SharedRealm.<init>(SharedRealm.java:187)
04-17 21:44:16.529  6538  6573 E AndroidRuntime: 	at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:229)
04-17 21:44:16.529  6538  6573 E AndroidRuntime: 	at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:204)
04-17 21:44:16.529  6538  6573 E AndroidRuntime: 	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:124)
04-17 21:44:16.529  6538  6573 E AndroidRuntime: 	at io.realm.Realm.getInstance(Realm.java:228)
04-17 21:44:16.529  6538  6573 E AndroidRuntime: 	at org.newstand.datamigration.repo.BKSessionRepoService.getRealm(BKSessionRepoService.java:36)
04-17 21:44:16.529  6538  6573 E AndroidRuntime: 	at org.newstand.datamigration.repo.OneTimeRealmRepoService.findLast(OneTimeRealmRepoService.java:83)
04-17 21:44:16.529  6538  6573 E AndroidRuntime: 	at org.newstand.datamigration.ui.activity.NavigatorActivity$11.run(NavigatorActivity.java:228)
04-17 21:44:16.529  6538  6573 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-17 21:44:16.529  6538  6573 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-17 21:44:16.529  6538  6573 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
04-17 21:44:16.534  1241  4875 W ActivityManager:   Force finishing activity org.newstand.datamigration/.ui.activity.NavigatorActivity
```

**Comment by Tornaco** [comment]
Crash in OnePlus3T
```
E REALM_JNI: jni: ThrowingException 5, Invalid argument in /home/cc/repo/realm/release/realm/realm-library/src/mainp/io_realm_internal_SharedRealm.cpp line 217, .
04-18 12:12:15.078  5505  9904 E REALM_JNI: Exception has been thrown: Unrecoverable error. Invalid argument in /home/cc/repo/realm/release/realm/realm-library/src/mainp/io_realm_internal_SharedRealm.cpp line 217
--------- beginning of crash
04-18 12:12:15.080  5505  9904 E AndroidRuntime: FATAL EXCEPTION: pool-3-thread-2
04-18 12:12:15.080  5505  9904 E AndroidRuntime: Process: org.newstand.datamigration, PID: 5505
04-18 12:12:15.080  5505  9904 E AndroidRuntime: io.realm.exceptions.RealmError: Unrecoverable error. Invalid argument in /home/cc/repo/realm/release/realm/realm-library/src/mainp/io_realm_internal_SharedRealm.cpp line 217
04-18 12:12:15.080  5505  9904 E AndroidRuntime: 	at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
04-18 12:12:15.080  5505  9904 E AndroidRuntime: 	at io.realm.internal.SharedRealm.<init>(SharedRealm.java:190)
04-18 12:12:15.080  5505  9904 E AndroidRuntime: 	at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:237)
04-18 12:12:15.080  5505  9904 E AndroidRuntime: 	at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:206)
04-18 12:12:15.080  5505  9904 E AndroidRuntime: 	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:127)
04-18 12:12:15.080  5505  9904 E AndroidRuntime: 	at io.realm.Realm.getInstance(Realm.java:229)
04-18 12:12:15.080  5505  9904 E AndroidRuntime: 	at org.newstand.datamigration.repo.ReceivedSessionRepoService.getRealm(ReceivedSessionRepoService.java:36)
04-18 12:12:15.080  5505  9904 E AndroidRuntime: 	at org.newstand.datamigration.repo.OneTimeRealmRepoService.size(OneTimeRealmRepoService.java:114)
04-18 12:12:15.080  5505  9904 E AndroidRuntime: 	at org.newstand.datamigration.ui.activity.NavigatorActivity$12.run(NavigatorActivity.java:249)
04-18 12:12:15.080  5505  9904 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-18 12:12:15.080  5505  9904 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-18 12:12:15.080  5505  9904 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
04-18 12:12:15.080  5505  9904 D AppTracker: App Event: crash
04-18 12:12:15.084  1406  2970 W ActivityManager:   Force finishing activity org.newstand.datamigration/.ui.activity.NavigatorActivity
04-18 12:12:15.084  5505  9903 E REALM_JNI: jni: ThrowingException 5, Invalid argument in /home/cc/repo/realm/release/realm/realm-library/src/mainp/io_realm_internal_SharedRealm.cpp line 217, .
04-18 12:12:15.084  5505  9903 E REALM_JNI: Exception has been thrown: Unrecoverable error. Invalid argument in /home/cc/repo/realm/release/realm/realm-library/src/mainp/io_realm_internal_SharedRealm.cpp line 217
04-18 12:12:15.085  5505  9903 I Process : Sending signal. PID: 5505 SIG: 9
04-18 12:12:15.098  2512  2672 D OPReportService: addMonitorFolder onEvent path=data_app_crash@2017-04-18-12_12_15_097.txt, event:128
04-18 12:12:15.098  2613  3051 D OPReportService: addMonitorFolder onEvent path=data_app_crash@2017-04-18-12_12_15_097.txt, event:128
04-18 12:12:15.099  1406  1463 W ActivityManager: Failed setting process group of 5505 to 1
04-18 12:12:15.099  1406  1463 I chatty  : uid=1000(system) ActivityManager expire 11 lines
```
